name: GitHub Secrets Practice

on:
  push:
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Check GitHub Secret
        run: |
          if [ -n "${{ secrets.PRACTICE_SECRET }}" ]; then
            echo "✅ GitHub Secret is available"
          else
            echo "❌ GitHub Secret is missing"
            exit 1
          fi
